config/routes.rb
Dmtri2::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root :to => "pages#home"

  resources :posts do
    member do
      put "soft_destroy"
      put "revive"
    end

    resources :comments do
      member do
        get "reply"
        post "create_reply"
        put "soft_destroy"
      end
    end
  end
  resources :comments
  resources :users do
    member do
      get "danger_zone"
    end
  end

  get "/about", :to => "static_pages#about"
  get "/help", :to => "static_pages#help"
  get "/contact", :to => "static_pages#contact"
  post "/mail_contact", :to => "static_pages#mail_contact"
  get "/user_agreement", :to => "static_pages#user_agreement"
  get "/privacy_policy", :to => "static_pages#privacy_policy"

  post "ratings/post_upvote"
  post "ratings/post_downvote"
  post "ratings/comment_upvote"
  post "ratings/comment_downvote"

  match 'posts/:id/:title' => 'posts#show', :as => :post_with_title

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :deleted, :anonymous, :comment_id, :post_id, :user_id
  attr_accessor :verification

  belongs_to :user
  belongs_to :post
  belongs_to :comment
  has_many :comments
  has_many :ratings

  validates :anonymous, inclusion: { in: [true, false] }
  validates :deleted, inclusion: { in: [true, false] }
  validates :content, presence: true
  validate :user_id_should_not_be_nil_if_anonymous_is_false
  
  after_create :push_post_top

  def user_id_should_not_be_nil_if_anonymous_is_false
    if user_id == nil && !anonymous
      errors.add(:anonymous, "value wasn't assigned correctly.")
    end
  end

  def net_rating
    net = 0
    ratings.each do |rating|
      if rating.updown
        net += 1
      else
        net -= 1
      end
    end
    net
  end
  
  private
  
    def push_post_top
      self.post.update_attribute('updated_at', Time.now)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :correct_user, only: [:edit, :update, :soft_destroy]
  before_filter :user_is_admin, only: :destroy

  def index
  end

  def show
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end

  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build
  end

  def create
    @post = Post.find(params[:post_id])

    if user_signed_in?
      comment_initialize

      if @comment.save
        @comment.ratings.create(:updown => true, :user_id => current_user.id) if user_signed_in?
        redirect_to @post
      else
        redirect_to @post
      end
    else
      if verify_recaptcha
        comment_initialize

        if @comment.save
          redirect_to @post
        else
          redirect_to @post
        end
      else
        redirect_to @post
      end
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    if @comment.update_attributes(params[:comment])
      redirect_to [@post, @comment]
    else
      render "edit"
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to @post
  end

  # other restful actions
  def reply
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @reply = @comment.comments.build
  end

  def create_reply
    @post = Post.find(params[:post_id])
    @parent = Comment.find(params[:id])
    @child = Comment.new(params[:comment])
    @child.comment_id = @parent.id
    @child.post_id = @post.id
    if user_signed_in?
      @child.user_id = current_user.id
      @child.anonymous = params[:comment][:anonymous]
    else
      @child.anonymous = true
    end

    if user_signed_in?
      if @child.save!
        redirect_to @post
      else
        render "reply"
      end
    else
      if verify_recaptcha
        if @child.save!
          redirect_to @post
        else
          render "reply"
        end
      else
        redirect_to reply_post_comment_path(@post, @parent)
      end
    end
  end

  def soft_destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    if @comment.update_attributes(deleted: true)
      redirect_to @post
    else
      render "edit"
    end
  end

  private

    def correct_user?(comment)
      user_signed_in? && (comment.user == current_user || current_user.admin)
      # comment.user || current_user == comment.user || !comment.anonymous
    end

    def user_is_mod?
      current_user.mod
    end

    def user_is_admin?
      current_user.admin
    end

    def correct_user
      post = Post.find(params[:post_id])
      comment = Comment.find(params[:id])
      redirect_to post_comment_path(post, comment) if !correct_user?(comment)
    end

    def user_is_admin
      comment = Comment.find(params[:id])
      redirect_to comment if !user_is_admin?
    end

    def comment_initialize
      @comment = nil
      if user_signed_in?
        @comment = current_user.comments.build(params[:comment])
      else
        @comment = Comment.new(params[:comment])
        @comment.anonymous = true
      end
      @comment.comment_id = params[:id]
      @comment.post_id = params[:post_id]
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.haml
- if !comment.anonymous || (comment.anonymous && user_signed_in? && comment.user_id == current_user.id)
  .comment
    .comment-body
      .comment-message= markdown.render(comment.content).html_safe
      .comment-message-below
        .comment-info.muted
          posted
          = time_ago_in_words(comment.created_at)
          by
          - if comment.anonymous
            anonymous
          - else
            = link_to comment.user.username, user_path(comment.user)
        .comment-actions
          - have_more_than_one_link = false
          - if current_user == comment.user
            - have_more_than_one_link = true
            = link_to "edit", edit_post_comment_path(post, comment), :class => "edit_comment"
            |
            = link_to "delete", soft_destroy_post_comment_path(post, comment), :method => :PUT, :remote => true, :class => "soft_delete"
            - if current_user.admin
              |
              = link_to "hard delete", [post, comment], :method => :DELETE, :class => "hard_delete"
          - if have_more_than_one_link
            |
          = link_to "permalink", post_comment_path(post, comment)

app/views/comments/_voting.html.haml
.upvote
  = form_for current_user.ratings.build(comment_id: comment.id), url: ratings_comment_upvote_path, remote: true do |f|
    = f.hidden_field :comment_id
    %button.btn.btn-link.upvote
      = "<i class='icon-arrow-up'></i>".html_safe
.downvote
  = form_for current_user.ratings.build(comment_id: comment.id), url: ratings_comment_downvote_path, remote: true do |f|
    = f.hidden_field :comment_id
    %button.btn.btn-link.downvote
      = "<i class='icon-arrow-down'></i>".html_safe

app/views/comments/edit.html.haml
%h1 Edit comment

= form_for [@post, @comment] do |f|
  .field
    .row.hidden-phone
      .span5
        = f.label :content, "Comment"
      .span5
        .fs08.muted.text-right=link_to "Formatting help", "#myModal", :role => "button", :data => {:toggle => "modal"}
    .row.visible-phone.expect-mobile
      .box-inline-left= f.label :content, "Comment"
      .box-inline-right.fs08.muted=link_to "Formatting help", "#myModal", :role => "button", :data => {:toggle => "modal"} 
    = f.text_area :content, :class => "input-block-level"

  .field
    = f.submit "Save changes", :class => "btn btn-primary"
    
= render :partial => "layouts/formatting_help"

app/views/comments/reply.html.haml
.comment
  .comment-body
    .comment-message= markdown.render(@comment.content).html_safe
    .comment-message-below
      .comment-info.muted
        posted
        = time_ago_in_words(@comment.created_at)
        by
        - if @comment.anonymous
          anonymous
        - else
          = link_to @comment.user.username, user_path(@comment.user)
      .comment-actions
        - if @comment.user && !@comment.anonymous
          |
          = link_to "edit", edit_post_comment_path(@post, @comment)
        |
        = link_to "show", post_comment_path(@post, @comment)
        |
        = link_to "delete", [@post, @comment], method: :DELETE
        - if @comment.user && !@comment.anonymous && !@comment.deleted
          |
          = link_to "soft_delete", soft_destroy_post_comment_path(@post, @comment), method: :PUT, remote: true
        |
        = link_to "reply", reply_post_comment_path(@post, @comment)


= form_for [@post, @reply], :url => create_reply_post_comment_path do |f|
  .field
    .row.hidden-phone
      .span5
        = f.label :content, "Reply"
      .span5
        .fs08.muted.text-right=link_to "Formatting help", "#myModal", :role => "button", :data => {:toggle => "modal"}
    .row.visible-phone.expect-mobile
      .box-inline-left= f.label :content, "Reply"
      .box-inline-right.fs08.muted=link_to "Formatting help", "#myModal", :role => "button", :data => {:toggle => "modal"} 
    
    - if user_signed_in?
      = f.text_area :content, rows: "10", :class => "input-block-level"
    - else
      = f.text_area :content, rows: "10", :class => "input-block-level", :placeholder => "You are commenting anonymously."
  - if user_signed_in?
    .field
      = f.label :anonymous do
        = f.check_box :anonymous
        Post anonymously
  - else
    = render "layouts/recaptcha/verification", :f => f

  .submit= f.submit "Submit", :class => "btn btn-primary"

= render :partial => "layouts/formatting_help"

app/views/comments/show.html.haml
.comment
  .comment-body
    .comment-message= simple_format(@comment.content)
    .comment-message-below
      .comment-info.muted
        posted
        = time_ago_in_words(@comment.created_at)
        by
        - if @comment.anonymous
          anonymous
        - else
          = link_to @comment.user.username, user_path(@comment.user)
      .comment-actions
        - if user_signed_in?
          - if current_user.admin
            = link_to "Edit", edit_post_comment_path(@post, @comment)
            |
            = link_to "Delete", soft_destroy_post_comment_path(@post, @comment), method: :PUT, remote: true
            |
            = link_to "PermaDelete", [@post, @comment], method: :DELETE
            |
            = link_to "Reply", reply_post_comment_path(@post, @comment)
          - elsif @comment.user == current_user
            = link_to "Edit", edit_post_comment_path(@post, @comment)
            |
            = link_to "Delete", soft_destroy_post_comment_path(@post, @comment), method: :PUT, remote: true
            |
            = link_to "Reply", reply_post_comment_path(@post, @comment)
          - else
            = link_to "Reply", reply_post_comment_path(@post, @comment)
        - else
          = link_to "Reply", reply_post_comment_path(@post, @comment)

  - if @comment.comments
    = render partial: "posts/children_comments", collection: @comment.comments, as: :comment