config/routes.rb
Dmtri2::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root :to => "pages#home"

  resources :posts do
    member do
      put "soft_destroy"
      put "revive"
    end

    resources :comments do
      member do
        get "reply"
        post "create_reply"
        put "soft_destroy"
      end
    end
  end
  resources :comments
  resources :users do
    member do
      get "danger_zone"
    end
  end

  get "/about", :to => "static_pages#about"
  get "/help", :to => "static_pages#help"
  get "/contact", :to => "static_pages#contact"
  post "/mail_contact", :to => "static_pages#mail_contact"
  get "/user_agreement", :to => "static_pages#user_agreement"
  get "/privacy_policy", :to => "static_pages#privacy_policy"

  post "ratings/post_upvote"
  post "ratings/post_downvote"
  post "ratings/comment_upvote"
  post "ratings/comment_downvote"

  match 'posts/:id/:title' => 'posts#show', :as => :post_with_title

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable
         # :recoverable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :password, :password_confirmation, :remember_me,
                  :username, :mod
                  # :email
  attr_protected :admin

  before_create :first_user_is_admin

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  # attr_accessor :login
  # attr_accessible :login

  has_many :comments
  has_many :posts
  has_many :ratings

  validates :username, presence: true, length: { minimum: 4 }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true, length: { minimum: 6 }

  validate :username_should_not_be

  def username_should_not_be
    not_allowed = ["admin", "moderator", "mod", "administrator"]
    if not_allowed.include?(username.downcase)
      errors.add(:username, ", #{username} is not allowed.")
    end
  end

  # this is for loggin in with username and email
  # def self.find_first_by_auth_conditions(warden_conditions)
  #   conditions = warden_conditions.dup
  #   if login = conditions.delete(:login)
  #     where(conditions).where(["lower(username) = :value = :value", { :value => login.downcase }]).first
  #     # where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
  #   else
  #     where(conditions).first
  #   end
  # end

  def upvote!(obj)
    if obj.is_a? Post
      upvote = ratings.create(updown: true, post_id: obj.id)
    elsif obj.is_a? Comment
      upvote = ratings.create(updown: true, comment_id: obj.id)
    else
      return false
    end
  end

  def downvote!(obj)
    if obj.is_a? Post
      upvote = ratings.create(updown: false, post_id: obj.id)
    elsif obj.is_a? Comment
      upvote = ratings.create(updown: false, comment_id: obj.id)
    else
      return false
    end
  end

  def total_points_for_posts
    points = 0
    posts.each do |post|
      points += post.net_rating
    end
    points
  end

  def total_points_for_comments
    points = 0
    comments.each do |comment|
      points += comment.net_rating
    end
    points
  end

  def total_points
    total_points_for_posts + total_points_for_comments
  end

  def posts_and_comments
    (posts + comments).sort! { |a, b|  b.created_at <=> a.created_at }
  end
  
  def non_anonymous_posts
    posts.select {|p| !p.anonymous }
  end
  
  def non_anonymous_comments
    comments.select {|c| !c.anonymous }
  end
  
  def non_anonymous_posts_and_comments
    (non_anonymous_posts + non_anonymous_comments).sort! { |a, b|  b.created_at <=> a.created_at }
  end
  
  def to_param
    username
  end

  private

    def first_user_is_admin
      if User.count < 1
        self.admin = true
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by_username(params[:id])
    @posts_and_comments = Kaminari.paginate_array(@user.posts_and_comments).page(params[:page]).per(20)
  end

  def destroy
    if current_user.admin == true
      @user = User.find_by_username(params[:id])
      @posts = @user.posts
      @comments = @user.comments

      @comments.destroy_all
      @posts.destroy_all
      @user.destroy

      flash[:success] = "The user was deleted."
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def danger_zone
    @user = User.find_by_username(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/danger_zone.haml
%h3 Cancel my account
%p
  Unhappy? #{link_to "Cancel my account", registration_path(@user), :data => { :confirm => "Are you sure?" }, :method => :delete}.
= link_to "Back", :back

app/views/users/show.html.haml
- provide(:title, @user.username + " page")

.row#show-user-header
  .span7
    %h1
      = @user.username
  .span3
    - if current_user == @user
      .btn-group#settings.pull-right
        %a{:class => 'btn dropdown-toggle', "data-toggle" => 'dropdown', :href => '#'}
          Settings
          %span{:class => 'caret'}
        %ul.dropdown-menu
          %li= link_to "Change password", edit_user_registration_path(@user)
          %li= link_to "Delete account", danger_zone_user_path(@user)
    - if current_user && current_user.admin
      %p
        current_sign_in_ip:
        = @user.current_sign_in_ip
      %p
        last_sign_in_ip:
        = @user.last_sign_in_ip
      %p
        = link_to 'Delete this user and posts', user_path(@user), method: :DELETE

.row
  .span10
    - @posts_and_comments.each do |element|
      - if element.instance_of?(Post)
        = render "posts/post", :post => element
      - else
        = render "comments/comment", :post => element.post, :comment => element
    = paginate @posts_and_comments
/ #show-user
/   #user-heading
/     %h1.page-header= @user.username
/   #user-feed