config/routes.rb
Dmtri2::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root :to => "pages#home"

  resources :posts do
    member do
      put "soft_destroy"
      put "revive"
    end

    resources :comments do
      member do
        get "reply"
        post "create_reply"
        put "soft_destroy"
      end
    end
  end
  resources :comments
  resources :users do
    member do
      get "danger_zone"
    end
  end

  get "/about", :to => "static_pages#about"
  get "/help", :to => "static_pages#help"
  get "/contact", :to => "static_pages#contact"
  post "/mail_contact", :to => "static_pages#mail_contact"
  get "/user_agreement", :to => "static_pages#user_agreement"
  get "/privacy_policy", :to => "static_pages#privacy_policy"

  post "ratings/post_upvote"
  post "ratings/post_downvote"
  post "ratings/comment_upvote"
  post "ratings/comment_downvote"

  match 'posts/:id/:title' => 'posts#show', :as => :post_with_title

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :content, :deleted, :anonymous
  attr_accessor :point, :verification, :urn

  paginates_per 20
  default_scope order('updated_at DESC')

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :ratings

  validates :anonymous, inclusion: { in: [true, false] }
  validates :deleted, inclusion: { in: [true, false] }
  validates :title, length: { maximum: 300 }
  validate :title_and_content_should_not_be_nil_together, :title_and_content_should_not_be_empty_together

  def title_and_content_should_not_be_nil_together
    if !title && !content
        errors.add(:title, "or content should have something")
    end
  end

  def title_and_content_should_not_be_empty_together
    if title.blank?
      errors.add(:title, "cannot be empty.")
    elsif content.blank?
      errors.add(:content, "cannot be empty.")
    end
  end

  # eventually need a new way to calculate top posts
  def points
    ratings.count
  end

  def comment_number
    comments.count
  end

  def self.top_posts
    find(:all, :conditions => {deleted: false}).each do |post|
      post.point = (post.net_rating-1)/(((Time.now-post.created_at)/3600)**1.8)
    end
    .sort! { |a, b|  a.point <=> b.point }.reverse
  end

  def net_rating
    net = 0
    ratings.each do |rating|
      if rating.updown
        net += 1
      else
        net -= 1
      end
    end
    net
  end
  
  def set_urn
    self.urn = "posts/#{self.id}/#{self.title}".titler
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_filter :authenticate_user!, only: [:edit, :update, :destory]
  before_filter :correct_user, only: [:edit, :update, :soft_destroy, :revive]
  before_filter :user_is_admin, only: :destroy

  def index
    @posts = Post.all
  end

  def new
    if user_signed_in?
      @post = current_user.posts.build
    else
      @post = Post.new
    end
  end

  def create
    @post = Post.new
    if user_signed_in?
      post_initialize

      if @post.save
        @post.ratings.create(:updown => true, :user_id => current_user.id) if user_signed_in?
        flash[:success] = "The post was created successfully."
        redirect_to post_with_title_path(@post, :title => @post.title.titler)
      else
        render 'new'
      end
    else
      if verify_recaptcha
        post_initialize

        if @post.save
          flash[:success] = "The post was created successfully."
          redirect_to post_with_title_path(@post, :title => @post.title.titler)
        else
          render 'new'
        end
      else
        render 'new'
      end
    end
  end

  def show
    @post = Post.find(URI::decode(params[:id]))
    @post.set_urn
    @comment = @post.comments.build
    @comments = Comment.where("post_id = ? AND comment_id is NULL", @post.id)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(params[:post])
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    Post.find(params[:id]).destroy
    redirect_to root_path
  end

  def soft_destroy
    @post = Post.find(params[:id])
    if correct_user?(@post) || user_is_mod? || user_is_admin?
      if @post.update_attributes(deleted: true)
        flash[:success] = "The post was deleted successfully."
        redirect_to @post
      else
        flash[:error] = "Deleting post failed."
        redirect_to @post
      end
    else
      redirect_to @post
    end
  end

  def revive
    @post = Post.find(params[:id])
    if @post.update_attributes(deleted: false)
      flash[:success] = "The post was revived successfully."
      redirect_to @post
    else
      flash[:error] = "The post revive failed."
      redirect_to @post
    end
  end

  private

    def correct_user?(post)
      current_user && (post.user == current_user || current_user.admin)
    end

    def user_is_mod?
      current_user.mod
    end

    def user_is_admin?
      if current_user
        current_user.admin?
      else
        false
      end
    end

    def correct_user
      post = Post.find(params[:id])
      redirect_to post_with_title_path(post, :title => post.title.titler) if !correct_user?(post)
    end

    def user_is_admin
      post = Post.find(params[:id])
      redirect_to post_with_title_path(post, :title => post.title.titler) if !user_is_admin?
    end

    def post_initialize
      @post = nil
      if user_signed_in?
        @post = current_user.posts.build(params[:post])
      else
        @post = Post.new(params[:post])
        @post.anonymous = true
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_children_comments.html.haml
.child
  .comment
    .comment-body
      .comment-message= markdown.render(comment.content).html_safe
      .comment-message-below
        .comment-info.muted
          posted
          = time_ago_in_words(comment.created_at)
          by
          - if comment.anonymous
            anonymous
          - else
            = link_to comment.user.username, user_path(comment.user) if comment.user
        
        - if user_signed_in?
          = link_to "PermaDelete", [@post, comment], method: :DELETE if current_user.admin
          - if current_user.admin || current_user == comment.user
            = link_to "Edit", edit_post_comment_path(@post, comment)
            |
            = link_to "Delete", soft_destroy_post_comment_path(@post, comment), method: :PUT, remote: true 
            |
          = link_to "Show", post_comment_path(@post, comment)
          |
          = link_to "Reply", reply_post_comment_path(@post, comment)
        - else
          = link_to "Show", post_comment_path(@post, comment)
          |
          = link_to "Reply", reply_post_comment_path(@post, comment)
    - if comment.comments
      = render :partial => "posts/children_comments", :collection => comment.comments, :as => :comment

app/views/posts/_comment.html.haml
= form_for [@post, @comment] do |f|
  .field
    .row
      .span10
        .fs08.muted.text-right=link_to "Formatting help", "#myModal", :role => "button", :data => {:toggle => "modal"}
    - if user_signed_in?
      = f.text_area :content, rows: "10", :class => "input-block-level"
    - else
      = f.text_area :content, rows: "10", :class => "input-block-level", :placeholder => "You are commenting anonymously."
  - if user_signed_in?
    .field
      = f.label :anonymous do
        = f.check_box :anonymous
        Post anonymously
  - else
    = render "layouts/recaptcha/verification", :f => f

  .submit
    = f.submit "Comment", :class => "btn btn-primary"

= render :partial => "layouts/formatting_help"

app/views/posts/_done_voting.html.haml
.points.done_voting
  .muted= post.points

app/views/posts/_post.haml
- if @home || !post.anonymous || (post.anonymous && user_signed_in? && post.user_id == current_user.id)
  .post
    .entry
      = link_to post.title, post_with_title_path(post, :title => post.title.titler), class: "title"
      .info
        Submitted
        / - shortened_time = time_ago_in_words(post.created_at)
        / = shortened_time[6..shortened_time.size]
        %span.submission_time= time_ago_in_words(post.created_at)
        by
        - if post.user && !post.anonymous
          = link_to post.user.username, user_path(post.user), :class => "link_to_submitter"
        - elsif post.user && post.anonymous && (post.user == current_user)
          = link_to post.user.username, user_path(post.user)
          %span.label anonymous
        - else
          anonymous
      .horizontal-buttons
        = link_to "#{post.comment_number} comments", post_with_title_path(post, :title => post.title.titler)+"#comments", :class => "link_to_comments"

app/views/posts/_social.html.erb
<a href="https://twitter.com/share" class="twitter-share-button" data-lang="en">Tweet</a>

<div class="fb-like" data-href="http://dmtri.com/<%= post.urn %>" data-width="The pixel width of the plugin" data-height="The pixel height of the plugin" data-colorscheme="light" data-layout="button_count" data-action="like" data-show-faces="true" data-send="false"></div>

<a href="http://www.tumblr.com/share" title="Share on Tumblr" style="display:inline-block; text-indent:-9999px; overflow:hidden; width:81px; height:20px; background:url('http://platform.tumblr.com/v1/share_1.png') top left no-repeat transparent;"></a>

app/views/posts/_voting.html.haml
.upvote
  = form_for current_user.ratings.build(post_id: post.id), url: ratings_post_upvote_path, remote: true do |f|
    = f.hidden_field :post_id
    %button.btn.btn-link.upvote
      = "<i class='icon-arrow-up'></i>".html_safe
.points
  = post.points
.downvote
  = form_for current_user.ratings.build(post_id: post.id), url: ratings_post_downvote_path, remote: true do |f|
    = f.hidden_field :post_id
    %button.btn.btn-link.downvote
      = "<i class='icon-arrow-down'></i>".html_safe

app/views/posts/edit.html.haml
%h1 Edit Post

= form_for @post do |f|
  .field
    = f.label :title
    = f.text_field :title, :class => "input-block-level"
  .field
    .row.hidden-phone
      .span5
        = f.label :content
      .span5
        .fs08.muted.text-right=link_to "Formatting help", "#myModal", :role => "button", :data => {:toggle => "modal"}
    .row.visible-phone.expect-mobile
      .box-inline-left= f.label :content
      .box-inline-right.fs08.muted=link_to "Formatting help", "#myModal", :role => "button", :data => {:toggle => "modal"} 
    = f.text_area :content, :class => "input-block-level"
  .field
    = f.label :anonymous do
      = f.check_box :anonymous
      Post anonymously
    
  .submit
    = f.submit "Submit", :class => "btn btn-primary"

= render :partial => "layouts/formatting_help"

app/views/posts/index.html.haml
%h1 all posts

- @posts.each do |p|
  %div
    = p.title
    by
    - if p.user && !p.anonymous
      = p.user.username
    - else
      anonymous
    %br/
    = p.content
    %br/
    = link_to "show", post_with_title_path(p, :title => post.title.titler)
    |
    = link_to "edit", edit_post_path(p)
    |
    = link_to "delete", post_path(p), method: :delete, remote: true

app/views/posts/new.html.haml
%h1
  New Post
  - if !user_signed_in?
    %span.label.label-info Post anonymously

= form_for @post do |f|
  = render "shared/flash_messages", :object => @post
  .field
    = f.label :title
    = f.text_field :title, :class => "input-block-level"
  .field
    .row.hidden-phone
      .span5
        = f.label :content
      .span5
        .fs08.muted.text-right=link_to "Formatting help", "#myModal", :role => "button", :data => {:toggle => "modal"}
    .row.visible-phone.expect-mobile
      .box-inline-left= f.label :content
      .box-inline-right.fs08.muted=link_to "Formatting help", "#myModal", :role => "button", :data => {:toggle => "modal"} 
    = f.text_area :content, :class => "input-block-level", :rows => 10
  - if user_signed_in?
    .field
      = f.label :anonymous do
        = f.check_box :anonymous
        Post anonymously
  - else
    = render "layouts/recaptcha/verification", :f => f

  .submit
    = f.submit "Submit", :class => "btn btn-primary"
  
= render :partial => "layouts/formatting_help"

app/views/posts/show.html.haml
- provide(:title, @post.title)
#post
  #post-heading
    %h2#title= link_to @post.title, post_with_title_path(@post, :title => @post.title.titler)
    #title-below.muted.row
      .span5
        posted
        = time_ago_in_words(@post.created_at)
        by
        - if @post.user && !@post.anonymous
          = link_to @post.user.username, user_path(@post.user), id: "username"
        - else
          #is-anonymous anonymous
      .span5.text-right
        = render :partial => "social", :locals => {:post => @post}

    #post-actions
      - if current_user
        - if current_user.admin?
          = link_to "PermaDelete", post_path(@post), method: :DELETE, class: "muted", confirm: "Are you sure you want to delete this post?"
          = link_to "Edit", edit_post_path(@post), :id => "post-delete"
          - if @post.deleted
            = link_to "Undelete", revive_post_path(@post), method: :PUT
          - else
            = link_to "Delete", soft_destroy_post_path(@post), method: :PUT, confirm: "Are you sure you want to delete this post?"
        - elsif @post.user && @post.user == current_user # && !@post.anonymous
          = link_to "Edit", edit_post_path(@post)
          = link_to "Delete", soft_destroy_post_path(@post), method: :PUT, confirm: "Are you sure you want to delete this post?"

    = render 'shared/flash_messages', :object => @post

    #content
      = markdown.render(@post.content).html_safe

  #post-comment
    = render "comment"

  %hr

  #comments
    - @comments.each do |comment|
      .comment
        .comment-body
          .comment-message= markdown.render(comment.content).html_safe
          .comment-message-below
            .comment-info.muted
              posted
              = time_ago_in_words(comment.created_at)
              by
              - if comment.anonymous
                anonymous
              - else
                - if comment.user
                  = link_to comment.user.username, user_path(comment.user)
                - else
                  *Deleted
            .comment-actions
              - if user_signed_in?
                = link_to "PermaDelete", [@post, comment], method: :DELETE if current_user.admin
                - if current_user.admin || current_user == comment.user
                  = link_to "Edit", edit_post_comment_path(@post, comment)
                  |
                  = link_to "Delete", soft_destroy_post_comment_path(@post, comment), method: :PUT, remote: true
                  |
                = link_to "Show", post_comment_path(@post, comment)
                |
                = link_to "Reply", reply_post_comment_path(@post, comment)
              - else
                = link_to "Show", post_comment_path(@post, comment)
                |
                = link_to "Reply", reply_post_comment_path(@post, comment)

        - if comment.comments
          = render partial: "children_comments", collection: comment.comments, as: :comment