config/routes.rb
Dmtri2::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root :to => "pages#home"

  resources :posts do
    member do
      put "soft_destroy"
      put "revive"
    end

    resources :comments do
      member do
        get "reply"
        post "create_reply"
        put "soft_destroy"
      end
    end
  end
  resources :comments
  resources :users do
    member do
      get "danger_zone"
    end
  end

  get "/about", :to => "static_pages#about"
  get "/help", :to => "static_pages#help"
  get "/contact", :to => "static_pages#contact"
  post "/mail_contact", :to => "static_pages#mail_contact"
  get "/user_agreement", :to => "static_pages#user_agreement"
  get "/privacy_policy", :to => "static_pages#privacy_policy"

  post "ratings/post_upvote"
  post "ratings/post_downvote"
  post "ratings/comment_upvote"
  post "ratings/comment_downvote"

  match 'posts/:id/:title' => 'posts#show', :as => :post_with_title

end

app/views/layouts/_favicon.html.haml
= favicon_link_tag 'favicon.ico', :rel => "shortcut icon"

app/views/layouts/_formatting_help.html.erb
<!-- modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Formatting help</h3>
  </div>
  <div class="modal-body">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Syntax</th>
          <th>Result</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>*italics*</td>
          <td><i>italics</i></td>
        </tr>
        <tr>
          <td>**bold**</td>
          <td><b>bold</b></td>
        </tr>
        <tr>
          <td>[Dmtri](http://dmtri.com)</td>
          <td><a href="http://dmtri.com">Dmtri</a></td>
        </tr>
        <tr>
          <td>
            - thing 1 </br>
            - thing 2 </br>
            - thing 3
          </td>
          <td>
            <ul>
              <li>thing 1</li>
              <li>thing 2</li>
              <li>thing 3</li>
            </ul>
          </td>
        </tr>
        <tr>
          <td>~~strikethrough~~</td>
          <td><strike>strikethrough</strike></td>
        </tr>
        <tr>
          <td>![alt text](http://i.imgur.com/w6tsORn.png)</td>
          <td><img src="http://i.imgur.com/w6tsORn.png" alt="alt text" /></td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>

app/views/layouts/_meta.html.haml
%meta{charset: "utf-8"}
%meta{name: "keywords", content: " dmtri, dmtri.com, post, comment, reply, anonymous, blog "}
%meta{name: "description", content: "dmtri: share thoughts anonymously"}
%meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}

app/views/layouts/_social.html.erb
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

<script src="http://platform.tumblr.com/v1/share.js"></script>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    = render "layouts/meta"

    = title_maker(yield(:title)).html_safe
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"

    /[if lt IE 9]
      %script{src: "http://html5shim.googlecode.com/svn/trunk/html5.js"}

    = render :partial => "layouts/social"

    = render "layouts/favicon"

    = csrf_meta_tags

  %body
    #wrap
      #push30
      .container
        .row
          .span2.visible-phone
            %h1#logo-phone= link_to application_name.capitalize, root_path
            .ul.nav.nav-tabs.nav-stacked#sidebar-pills
              - if user_signed_in?
                %li= link_to current_user.username, user_path(current_user)
                %li= link_to "Sign out", destroy_user_session_path, :method => :delete
              - else
                %li= link_to "Sign up", new_user_registration_path
                %li= link_to "Sign in", new_user_session_path
              %li= link_to "Post", new_post_path
          .span10#main
            = yield
          .span2.hidden-phone#sidebar
            %h1#logo.hidden-tablet= link_to application_name.capitalize, root_path
            %h1#logo-tablet.visible-tablet= link_to application_name.capitalize, root_path
            .ul.nav.nav-tabs.nav-stacked#sidebar-pills
              - if user_signed_in?
                %li= link_to current_user.username, user_path(current_user)
                %li= link_to "Sign out", destroy_user_session_path, :method => :delete
              - else
                %li= link_to "Sign up", new_user_registration_path
                %li= link_to "Sign in", new_user_session_path
              %li= link_to "Post", new_post_path
      #push180
    #footer
      .container.footer-content
        .row
          .span6
            %ul#footer-navigation
              %li.first= link_to application_name.capitalize, root_path, :id => "footer-logo"
              %li= link_to "About", about_path
              %li= link_to "Help", help_path
              %li= link_to "Contact", contact_path
            %ul#footer-navigation.visible-phone
              %li= link_to "Twitter"
              %li= link_to "Facebook"
              %li= link_to "Tumblr"
          .span6.text-right.visible-desktop.visible-tablet
            = link_to image_tag('twitterbutton15x15px.png', :width => "30px"), 'https://twitter.com/DmtriDotCom', :class => "social-share"
            = link_to image_tag('fbbutton15x15px.png', :width => "30px"), "https://www.facebook.com/DmtriDotCom", :class => "social-share"
            = link_to image_tag('tumblrbutton15x15px.png', :width => "30px"), "http://dmtridotcom.tumblr.com/"
        .row
          .span12
            %p.fs07.muted
              By using this site, you agree to the
              = link_to "User Agreement", user_agreement_path
              and
              = link_to "Privacy Policy", privacy_policy_path
              \.
              %br
              © 2013 -
              = Time.now.year
              Dmtri. All rights reserved.



    / google analytics
    :javascript
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-28018879-6']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();